### ISSUE TITLE
oci_database_autonomous_database doesn't allow different free form tags in remote standby database when creating, but allow update

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/oracle/oci v4.113.0

### Affected Resource(s)

oci_database_autonomous_database

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 

freeform_tags = {
  location = "remote_standby_location"
}
```

### Expected Behavior

standby database, especially remote standby database, should allow different freeform tags, at least the location is different.

### Actual Behavior

When creating remote standby, if the freeform tags are different, creation will fail which doesn't make sense. Furthermore, once the remote standby, the freeform tags can be updated to be different from the primary.

### Steps to Reproduce

1. when creating remote standby, set the freeform tags to be different from the primary.
2. terraform apply will fail
3. change the freeform tags to be the same as primary, remote standby can be created successfully now.
4. then change the freeform tags on the standby to be different from primary, now it's ok.

NOTE: there is an unrelated bug when updating standby configuration, such as operations insight status, database management status and freeform tags, updates will success, but terraform will fail due to checking for "available" status on the database when it's actually "standby". reported here: https://github.com/oracle/terraform-provider-oci/issues/1832

**Comment by tf-oci-pub** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by xiaoditao1** [comment]
”When creating remote standby, if the freeform tags are different, creation will fail“ please provide opc-request-id or the error message here.

**Comment by navg-orcl** [comment]
We will be blocking the update of free form tags on the remote standby

**Comment by luckeyca** [comment]
Hi @navg-orcl, it does NOT make any sense to block update free form tags on remote standby database because tags are NOT part of the database internal structure, but an important flag for cloud resource which has nothing to do with the database lifecycle state. If you block update to resource tag, it will create problems for billing and inventory etc., Please fix this properly

**Comment by karthikoracle1993** [comment]
This issue should be fixed now. Please verify and close this issue.

**Comment by luckeyca** [comment]
Hi @karthikoracle1993, thanks for the update. will test and report back

**Comment by luckeyca** [comment]
Hi @karthikoracle1993, the bug was not fully fixed. now. when during initial deployment(create primary and standby from scratch), it does allow different tags. for example, I have primary as {location = toronto}, standby as {location=standby}. However, after deployment, I tried to add one tag on both, primary with {database_role = primary} standby as {database_role = remote_standby}. primary worked, but standby failed. It's still the old issue when updating cloud resource settings that are NOT related to database internals, the code is wrongly depending on database status, in this case standby which should only prevent database internal changes, NOT cloud resource level changes which have nothing to do with database internal operations. see the error below

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.SSC_CORE_terraform_module_adb_cicd_test_primary_adb.oci_database_autonomous_database.this[0] will be updated in-place
  ~ resource "oci_database_autonomous_database" "this" {
      ~ freeform_tags                                  = {
          + "database_role"         = "primary"
            # (9 unchanged elements hidden)
        }
        id                                             = "ocid1.autonomousdatabase.oc1.ca-toronto-1.an2g6ljr5xeuumqazjbvmkxcnb2j3acswphe7wta5ww53ky7oahdidsi5pza"
        # (82 unchanged attributes hidden)

        # (10 unchanged blocks hidden)
    }

  # module.SSC_CORE_terraform_module_adb_cicd_test_standby_adb.oci_database_autonomous_database.this[0] will be updated in-place
  ~ resource "oci_database_autonomous_database" "this" {
      ~ freeform_tags                                  = {
          + "database_role"         = "remote_standby"
            # (9 unchanged elements hidden)
        }
        id                                             = "ocid1.autonomousdatabase.oc1.ca-montreal-1.an4xkljr5xeuumqateyylxckh4wkbozjyd5zkq6jzvdjl2t7wwyhpc4qotra"
        # (79 unchanged attributes hidden)

        # (10 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
module.SSC_CORE_terraform_module_adb_cicd_test_primary_adb.oci_database_autonomous_database.this[0]: Modifying... [id=ocid1.autonomousdatabase.oc1.ca-toronto-1.an2g6ljr5xeuumqazjbvmkxcnb2j3acswphe7wta5ww53ky7oahdidsi5pza]
module.SSC_CORE_terraform_module_adb_cicd_test_primary_adb.oci_database_autonomous_database.this[0]: Still modifying... [id=ocid1.autonomousdatabase.oc1.ca-toronto...xcnb2j3acswphe7wta5ww53ky7oahdidsi5pza, 10s elapsed]
module.SSC_CORE_terraform_module_adb_cicd_test_primary_adb.oci_database_autonomous_database.this[0]: Still modifying... [id=ocid1.autonomousdatabase.oc1.ca-toronto...xcnb2j3acswphe7wta5ww53ky7oahdidsi5pza, 20s elapsed]
module.SSC_CORE_terraform_module_adb_cicd_test_primary_adb.oci_database_autonomous_database.this[0]: Modifications complete after 23s [id=ocid1.autonomousdatabase.oc1.ca-toronto-1.an2g6ljr5xeuumqazjbvmkxcnb2j3acswphe7wta5ww53ky7oahdidsi5pza]
module.SSC_CORE_terraform_module_adb_cicd_test_standby_adb.oci_database_autonomous_database.this[0]: Modifying... [id=ocid1.autonomousdatabase.oc1.ca-montreal-1.an4xkljr5xeuumqateyylxckh4wkbozjyd5zkq6jzvdjl2t7wwyhpc4qotra]
module.SSC_CORE_terraform_module_adb_cicd_test_standby_adb.oci_database_autonomous_database.this[0]: Still modifying... [id=ocid1.autonomousdatabase.oc1.ca-montrea...ckh4wkbozjyd5zkq6jzvdjl2t7wwyhpc4qotra, 10s elapsed]
module.SSC_CORE_terraform_module_adb_cicd_test_standby_adb.oci_database_autonomous_database.this[0]: Still modifying... [id=ocid1.autonomousdatabase.oc1.ca-montrea...ckh4wkbozjyd5zkq6jzvdjl2t7wwyhpc4qotra, 20s elapsed]
╷
│ Error: During update, Terraform expected the resource to reach state(s): AVAILABLE, but the service reported unexpected state: STANDBY.
│
│   with module.SSC_CORE_terraform_module_adb_cicd_test_standby_adb.oci_database_autonomous_database.this[0],
│   on ../../../main.tf line 21, in resource "oci_database_autonomous_database" "this":
│   21: resource "oci_database_autonomous_database" "this" {
```

**Comment by luckeyca** [comment]
confirmed this was fixed
